### ISSUE TITLE
Ball physics

### ISSUE THREAD

**Issue by erl67** [erl67/Breakout3D#4]
Bounce speed
Bounce direction
Angular velocity

Physics changes on hitting blocks - Slow down, head towards bottom

**Comment by YanboWang76** [comment]
One way to set the ball physics:
1.Remove the gravity of the ball.

2.After launching from the pad, the ball will always move at a constant speed (unless we decide to add some bonus which can change the speed of the ball).

3.The speed of ball will not be changed if the ball hits a block or the edge of the play area. However, its direction will change to the regular reflection direction.

4.On hitting the pad, the ball will change to a direction based on the point that it hits the pad. For example, if the ball hits the pad right in the middle, the ball will be bounced back vertically; If the ball hits the pad around the edge, it will be bounced back at an angle of 60° away from vertical; If the ball hits somewhere in between, it will be bounced back at an angle between 60° and 0, I think we can write a function to do that. This will make it easier for the player to hit all of the blocks.

5.(Optional) To make law 4 looks more realistic, we can change the shape of the pad into some kind of arc shape instead of just a pad, which explains why a ball will be bounced back with different angles. You can see that in the link below.

To see an example of what I wrote above, you can check this link, I took many of those ideas from this game: 
https://www.youtube.com/watch?v=cBIedv-i8eo
It's a great game, I had lots of fun when I was playing it at ten thou.
